// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Footer: typeof import("./src/components/Modal/Footer.vue")["default"];
    Modal: typeof import("./src/components/Modal/Modal.vue")["default"];
    MouseMove: typeof import("./src/components/MouseMove.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SyncLocalStorage: typeof import("./src/components/SyncLocalStorage.vue")["default"];
  }
}
